language: node_js
node_js:
  - 12

addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

script:
  # start server in the background
  - npm run start:ci &
  # run all Cypress tests and record on the dashboard
  - npm run cy:run
  
  - kill $(jobs -p) || true